package com.onlinebanking.notification.entity;

public enum NotificationType {
    TRANSACTION_SUCCESS,
    TRANSACTION_FAILED,
    SECURITY,
    TRANSACTION_PENDING, SECURITY_LOGIN, SECURITY_PASSWORD, SECURITY_OTP, SECURITY_FRAUD,
    APPROVAL_BENEFICIARY, APPROVAL_LOAN, APPROVAL_CARD,
    UPDATE_KYC, UPDATE_CARD, UPDATE_ACCOUNT,
    OFFER_CASHBACK, OFFER_PROMOTION,
    BILL_REMINDER, EMI_REMINDER
}
