"""
FinEdge Fraud Detection Service — Step 13: Updated Integration Tests

Tests cover four scenarios:
  1. Health endpoint — asserts new modelStatus field exists (either value valid)
  2. Fraud check — ML model mode (artifacts present) — shape/type assertions only
  3. Fraud check — STUB fallback mode (ML_ARTIFACTS_DIR pointed at empty/nonexistent dir)
  4. Fraud check — Unauthenticated request (unchanged)

NOTE ON TEST DESIGN (Step 13 update):
======================================
The previous test (test_fraud_check_stub_authenticated) asserted riskScore == 85.0.
This is only valid in stub mode. In ML mode the score is a model probability × 100,
which depends on the artifact and feature vector — it cannot be hardcoded.

Strategy:
  - ML mode tests: assert shape, types, valid enum values, modelVersion != "stub-v0"
  - Stub mode tests: assert original deterministic scores (85.0 / 55.0 / 15.0)
                     using ML_ARTIFACTS_DIR override to force stub fallback

STUB FALLBACK FORCING:
========================
The model_loader module uses a module-level _registry dict populated at startup.
To force stub mode in tests without restarting the app, we directly reset the
_registry["loaded"] flag via monkeypatching. This is the simplest approach for
a college project — a production service would use dependency injection.
"""

import base64
import os
from datetime import datetime, timedelta
from unittest.mock import patch

import jwt
import pytest
from fastapi.testclient import TestClient

from app.config.settings import settings
from app.main import app
from app import model  # noqa — ensures model package is importable

client = TestClient(app)

# Path to real synthetic artifacts generated by Step 12
REAL_ARTIFACTS_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "ml", "artifacts")
)
NONEXISTENT_ARTIFACTS_DIR = "/nonexistent/path/to/artifacts"


# ---------------------------------------------------------------------------
# JWT helper
# ---------------------------------------------------------------------------

def get_test_jwt() -> str:
    try:
        key = base64.b64decode(settings.JWT_SECRET)
    except Exception:
        key = settings.JWT_SECRET.encode("utf-8")

    payload = {
        "sub": "testuser",
        "role": "CUSTOMER",
        "exp": datetime.utcnow() + timedelta(hours=1)
    }
    return jwt.encode(payload, key, algorithm="HS256")


# ---------------------------------------------------------------------------
# 1. Health endpoint
# ---------------------------------------------------------------------------

def test_health_check_has_model_status():
    """Health endpoint must include modelStatus (either ML_MODEL_LOADED or STUB_FALLBACK)."""
    response = client.get("/api/v1/health")
    assert response.status_code == 200
    data = response.json()
    assert data["service"] == "fraud-detection-service"
    assert data["status"] == "UP"
    assert "modelStatus" in data, "modelStatus field missing from health response"
    assert data["modelStatus"] in ("ML_MODEL_LOADED", "STUB_FALLBACK")
    assert "modelVersion" in data
    assert "artifactsDir" in data


# ---------------------------------------------------------------------------
# 2. Fraud check — ML model mode (real synthetic artifacts)
# ---------------------------------------------------------------------------

def test_fraud_check_ml_mode_response_shape():
    """
    When ML artifacts are present, fraud/check must return a valid, well-shaped response.
    We do NOT assert a specific riskScore — ML output depends on the artifact.
    """
    from app.model import model_loader
    if not model_loader.is_model_loaded():
        pytest.skip(
            "ML model not loaded (artifacts not present or load failed). "
            "Run ml/training/train_models.py first, then re-run tests."
        )

    token = get_test_jwt()
    headers = {"Authorization": f"Bearer {token}"}
    payload = {
        "transactionRef": "TXN-ML-001",
        "type": "TRANSFER",
        "fromAccountNumber": "ACC-1001",
        "toAccountNumber": "ACC-1002",
        "amount": 15000.0,
        "initiatedByUsername": "testuser",
        "timestamp": "2024-03-15T02:30:00Z",   # late-night — should trigger indicator
    }
    response = client.post("/api/v1/fraud/check", json=payload, headers=headers)
    assert response.status_code == 200

    data = response.json()
    assert data["transactionRef"] == "TXN-ML-001"
    assert 0.0 <= data["riskScore"] <= 100.0, "riskScore must be in [0, 100]"
    assert data["decision"] in ("LOW_RISK", "REVIEW", "HIGH_RISK")
    assert isinstance(data["indicators"], list)
    assert len(data["indicators"]) > 0
    assert data["modelVersion"] != "stub-v0", "ML mode must not report stub-v0 version"
    assert "evaluatedAt" in data


def test_fraud_check_ml_mode_modelversion_not_stub():
    """Verify modelVersion reflects the real model artifact name when loaded."""
    from app.model import model_loader
    if not model_loader.is_model_loaded():
        pytest.skip("ML model not loaded — skipping.")

    token = get_test_jwt()
    headers = {"Authorization": f"Bearer {token}"}
    payload = {
        "transactionRef": "TXN-ML-002",
        "type": "DEPOSIT",
        "amount": 500.0,
        "initiatedByUsername": "testuser",
    }
    response = client.post("/api/v1/fraud/check", json=payload, headers=headers)
    assert response.status_code == 200
    assert response.json()["modelVersion"] != "stub-v0"


# ---------------------------------------------------------------------------
# 3. Fraud check — STUB fallback mode (ML_ARTIFACTS_DIR forced to nonexistent)
# ---------------------------------------------------------------------------

def test_fraud_check_stub_fallback_high_risk():
    """
    With ML model forcibly disabled (stub mode), the original amount-threshold
    heuristic must still return 85.0 / HIGH_RISK for amount > $10,000.
    """
    from app.model import model_loader

    # Temporarily force stub mode by patching the registry
    original_loaded = model_loader._registry["loaded"]
    original_version = model_loader._registry["model_version"]
    try:
        model_loader._registry["loaded"] = False
        model_loader._registry["model_version"] = "stub-v0"

        token = get_test_jwt()
        headers = {"Authorization": f"Bearer {token}"}
        payload = {
            "transactionRef": "TXN-STUB-100",
            "type": "TRANSFER",
            "fromAccountNumber": "1001",
            "toAccountNumber": "1002",
            "amount": 15000.0,
            "initiatedByUsername": "testuser",
        }
        response = client.post("/api/v1/fraud/check", json=payload, headers=headers)
        assert response.status_code == 200
        data = response.json()
        assert data["transactionRef"] == "TXN-STUB-100"
        assert data["decision"] == "HIGH_RISK"
        assert data["riskScore"] == 85.0
        assert data["modelVersion"] == "stub-v0"
    finally:
        # Always restore original state
        model_loader._registry["loaded"] = original_loaded
        model_loader._registry["model_version"] = original_version


def test_fraud_check_stub_fallback_review():
    """Stub mode: amount > $5,000 must return 55.0 / REVIEW."""
    from app.model import model_loader

    original_loaded = model_loader._registry["loaded"]
    original_version = model_loader._registry["model_version"]
    try:
        model_loader._registry["loaded"] = False
        model_loader._registry["model_version"] = "stub-v0"

        token = get_test_jwt()
        headers = {"Authorization": f"Bearer {token}"}
        payload = {
            "transactionRef": "TXN-STUB-101",
            "type": "WITHDRAWAL",
            "amount": 7500.0,
            "initiatedByUsername": "testuser",
        }
        response = client.post("/api/v1/fraud/check", json=payload, headers=headers)
        assert response.status_code == 200
        data = response.json()
        assert data["decision"] == "REVIEW"
        assert data["riskScore"] == 55.0
        assert data["modelVersion"] == "stub-v0"
    finally:
        model_loader._registry["loaded"] = original_loaded
        model_loader._registry["model_version"] = original_version


def test_fraud_check_stub_fallback_low_risk():
    """Stub mode: amount <= $5,000 must return 15.0 / LOW_RISK."""
    from app.model import model_loader

    original_loaded = model_loader._registry["loaded"]
    original_version = model_loader._registry["model_version"]
    try:
        model_loader._registry["loaded"] = False
        model_loader._registry["model_version"] = "stub-v0"

        token = get_test_jwt()
        headers = {"Authorization": f"Bearer {token}"}
        payload = {
            "transactionRef": "TXN-STUB-102",
            "type": "DEPOSIT",
            "amount": 250.0,
            "initiatedByUsername": "testuser",
        }
        response = client.post("/api/v1/fraud/check", json=payload, headers=headers)
        assert response.status_code == 200
        data = response.json()
        assert data["decision"] == "LOW_RISK"
        assert data["riskScore"] == 15.0
        assert data["modelVersion"] == "stub-v0"
    finally:
        model_loader._registry["loaded"] = original_loaded
        model_loader._registry["model_version"] = original_version


# ---------------------------------------------------------------------------
# 4. Unauthenticated request (unchanged from Step 12)
# ---------------------------------------------------------------------------

def test_fraud_check_unauthenticated():
    """Requests without a valid JWT must be rejected with 401 or 403."""
    payload = {
        "transactionRef": "TXN-UNAUTH-001",
        "type": "DEPOSIT",
        "amount": 500.0,
        "initiatedByUsername": "testuser",
    }
    response = client.post("/api/v1/fraud/check", json=payload)
    assert response.status_code in (401, 403)


# ---------------------------------------------------------------------------
# 5. Model loader unit test — graceful fallback on missing artifacts
# ---------------------------------------------------------------------------

def test_model_loader_graceful_fallback_on_missing_dir():
    """
    load_model() pointed at a nonexistent directory must NOT raise an exception.
    Service remains in stub mode (_registry["loaded"] == False after the call).
    """
    from app.model import model_loader

    # Save current state
    original_registry = dict(model_loader._registry)
    try:
        # Reset to unloaded state
        model_loader._registry.update({
            "loaded": False, "model": None, "preprocessor": None,
            "model_name": None, "model_version": "stub-v0",
            "preprocessor_type": None, "metadata": {},
        })
        # This must not raise
        model_loader.load_model(NONEXISTENT_ARTIFACTS_DIR)
        assert model_loader._registry["loaded"] is False, \
            "Registry must remain unloaded when artifacts dir is missing"
        assert model_loader.is_model_loaded() is False
    finally:
        model_loader._registry.update(original_registry)
